def dose18plus(update: Update, context: CallbackContext) -> int:
    """Show new choice of buttons"""
    query = update.callback_query
    query.answer()
    keyboard = [
        [
            InlineKeyboardButton("Voltar", callback_data=str(LOC)),
            InlineKeyboardButton("Home", callback_data=str(START)),
            InlineKeyboardButton("Close", callback_data=str(END)),
        ]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    query.edit_message_text(
        text='''
        Primeira dose
        Tem 18 anos ou mais. 
        
        Local de vacina 1...
        Local de vacina 2...
        Local de vacina 3...
        Local de vacina 4...
        Local de vacina 5...
        Local de vacina 6...
        Local de vacina 7...
        Local de vacina 8...
        Local de vacina 9...
        Local de vacina 10...
        Local de vacina 11...
        ''', reply_markup=reply_markup
    )
    return FIRST